package com.tch.filesystem.model;

public class Directory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.fid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.pid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.uid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory.fid
     *
     * @return the value of directory.fid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory.fid
     *
     * @param fid the value for directory.fid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory.pid
     *
     * @return the value of directory.pid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory.pid
     *
     * @param pid the value for directory.pid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory.uid
     *
     * @return the value of directory.uid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory.uid
     *
     * @param uid the value for directory.uid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}