package com.tch.filesystem.model;

public class LoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.lid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.ltime
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    private Long ltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.lip
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    private String lip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.uid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.lid
     *
     * @return the value of loginlog.lid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.lid
     *
     * @param lid the value for loginlog.lid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.ltime
     *
     * @return the value of loginlog.ltime
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public Long getLtime() {
        return ltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.ltime
     *
     * @param ltime the value for loginlog.ltime
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public void setLtime(Long ltime) {
        this.ltime = ltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.lip
     *
     * @return the value of loginlog.lip
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public String getLip() {
        return lip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.lip
     *
     * @param lip the value for loginlog.lip
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public void setLip(String lip) {
        this.lip = lip == null ? null : lip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.uid
     *
     * @return the value of loginlog.uid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.uid
     *
     * @param uid the value for loginlog.uid
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}