package com.tch.filesystem.mapper;

import com.tch.filesystem.model.Directory;
import com.tch.filesystem.model.DirectoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DirectoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    long countByExample(DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int deleteByExample(DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int insert(Directory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int insertSelective(Directory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    List<Directory> selectByExample(DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") Directory record, @Param("example") DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int updateByExample(@Param("record") Directory record, @Param("example") DirectoryExample example);
}