package com.tch.filesystem.mapper;

import com.tch.filesystem.model.FilePath;
import com.tch.filesystem.model.FilePathExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilePathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    long countByExample(FilePathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int deleteByExample(FilePathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int insert(FilePath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int insertSelective(FilePath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    List<FilePath> selectByExample(FilePathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    FilePath selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") FilePath record, @Param("example") FilePathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int updateByExample(@Param("record") FilePath record, @Param("example") FilePathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int updateByPrimaryKeySelective(FilePath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_path
     *
     * @mbg.generated Tue Nov 19 01:22:11 CST 2019
     */
    int updateByPrimaryKey(FilePath record);
}